service: aws-back-culqui
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  region: sa-east-1
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-ssm-fetch

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!.serverless/**"
    - "!package-lock.json"
    - "!tsconfig.json"
    - "!package.json"
    - "!README.md"

custom:
  serverlessSsmFetch:
    DB_CNN_STRING: /db_cnn_string~true

functions:
  - ${file(./structure-aws/functions/create-token.yml)}
  - ${file(./structure-aws/functions/get-card.yml)}